version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    env_file: .env
    environment:
      - MYSQL_DATABASE= $MYSQL_DATABASE
      # So you don't have to use root, but you can if you like
      - MYSQL_USER= $MYSQL_USER
      # You can use whatever password you like
      - MYSQL_PASSWORD= $MYSQL_PASSWORD
      # Password for root access
      - MYSQL_ROOT_PASSWORD= $MYSQL_ROOT_PASS
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /opt/mysql_data:/var/lib/mysql
  app:
    depends_on:
      - db
    build: .
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - "3000:3000"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
# Names our volume
# volumes:
#   my-db:
#     driver: local
